version: "2"

before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  -
    id: control-controls-darwin
    ldflags:
      - -s -w -X github.com/pepabo/control-controls.version={{.Version}} -X github.com/pepabo/control-controls.commit={{.FullCommit}} -X github.com/pepabo/control-controls.date={{.Date}} -X github.com/pepabo/control-controls/version.Version={{.Version}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  -
    id: control-controls-linux
    ldflags:
      - -s -w -X github.com/pepabo/control-controls.version={{.Version}} -X github.com/pepabo/control-controls.commit={{.FullCommit}} -X github.com/pepabo/control-controls.date={{.Date}} -X github.com/pepabo/control-controls/version.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
archives:
  -
    id: control-controls-archive
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: darwin
        format: zip
    files:
      - CREDITS
      - README.md
      - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  -
    id: control-controls-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
      - control-controls-linux
    homepage: https://github.com/pepabo/control-controls
    maintainer: 'GMO Pepabo, inc.'
    description: control-controls control controls of AWS Security Hub across all regions.
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    epoch: 1
